src/common/upload.ts

The SDK should upload to arweave.net by default. Currently, you must provide `defaultTurboConfgiuration` when instantiating a `TurboAuthenticatedClient`, otherwise uploads will go to arweave.dev

fix(upload): update the default upload service URL

---

src/common/factory.ts
src/common/http.ts
src/common/logger.ts
src/common/payment.ts
src/common/upload.ts
src/node/factory.ts
src/node/signer.ts
src/types.ts
src/utils/axiosClient.ts
src/web/factory.ts
src/web/signer.ts

This allows users to configure the global logger (currently implemented with Winston) to give helpful debugging logs. We can continue to add debug logs, as well as identify spots where performance metrics may be helpful.
Example:
```
TurboFactory.setLogLevel('debug');
TurboFactory.setLogFormat('json');
```
Logs:
```
{"client":"turbo-sdk","level":"debug","message":"Signing data item...","timestamp":"2023-11-09T21:05:41.719Z","version":"1.0.2"}
{"client":"turbo-sdk","level":"debug","message":"Successfully signed data item...","timestamp":"2023-11-09T21:05:52.522Z","version":"1.0.2"}
{"client":"turbo-sdk","level":"debug","message":"Uploading signed data item...","timestamp":"2023-11-09T21:05:52.523Z","version":"1.0.2"}
{"client":"turbo-sdk","level":"debug","loaded":"1044 …
```

feat(logger): add configurable global logger

---

src/common/http.ts

We found a bug that was causing large amount of backpressure when uploading larger files (3GiB+) via the SDK. Axios loads the stream into memory, and backpressure is created while posting to `https`. We need to look further into any unintended consequeneces of this change, but it does allow larger files to be uploaded.
Fixes PE-5001

fix(axios): set `maxRedirects` to `0` on our axios instances

---

package.json

The types path is correct, but the referenced index path is not.

fix(exports): web exports reference an invalid build path

---

.github/workflows/build.yml
docker-compose.yml
package.json
tests/helpers.ts
tests/turbo.node.test.ts
tests/turbo.web.test.ts

This allows tests to run against a local upload and payment service, rather than hitting dev instances. It's configurable when running.

chore(test): add ability for running tests against local docker-compose

---

.github/workflows/pr.yml

The goal of this branch is to run on merges to main. It'll create PRs back to our `alpha` and `beta` branches

chore(github): create auto generated PRs on merges to main

---

.github/workflows/build.yml
package.json
yarn.lock

The 0.11.0 version of arbundles introduces a breaking change to ArconnectSigner causing issues

fix(arbundles): pin arbundles to 0.9.9 and run tests locally

---

.env.test
docker-compose.yml
package.json

Two tests now failing related to credit transactions.
Remaining test failures:
```
1) Node environment
TurboUnauthenticatedNodeClient
submitFundTransaction()
should properly submit an existing payment transaction ID to the Turbo Payment Service for processing:
FailedRequestError: Failed request: 404: Not Found
at TurboHTTPService.post (file:///Users/dylanfiedler/Documents/ardrive/turbo/turbo-sdk/src/common/http.ts:109:13)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at async TurboUnauthenticatedPaymentService.submitFundTransaction (file:///Users/dylanfiedler/Documents/ardrive/turbo/turbo-sdk/src/common/payment.ts:178:22)
at async Context.<anonymous> (file:///Users/dylanfiedler/Documents/ardrive/turbo/turbo-sdk/tests/turbo.node.test.ts:241:44)
2) Browser …
```

chore: add script to mine blocks in docker compose

---

package.json
run-tests.sh

Allows you to run scoped tests via `yarn test -g "fund"`

chore: allow for running tests dynamically

---

README.md
src/common/signer.ts

This prevents clients from having to install `arbundles` separately from our SDK and gives us the ability to pin to specific implementations if necessary

feat(signers): exports arbundles ArconnectSigner and ArweaveSigner

---

README.md
package.json
yarn.lock

The build outputs for web should not be the bundled version. This causes issues in bundlers (e.g. esbuild, webpack, etc.). As a result, polyfills must be provided by clients - which was already reccomended, now this will make it required.

fix(build): update build outputs for web and README

---

README.md
src/cli/cli.ts
src/cli/commands.ts
src/cli/types.ts
src/cli/utils.ts
src/common/currency.ts
src/common/payment.ts
src/types.ts

```sh
> node lib/esm/cli/cli.js top-up --wallet-file ../wallets/zarweave-keyfile-jaxl_dxqJ00gEgQazGASFXVRvO4h-Q0_vnaLtuOUoWU_dereks.json --value 10      
Got Checkout Session
{"url":"https://checkout.stripe.com/c/pay/cs_live_a14J22sFvvu5jifp9dlIS0869DXMzMS78B0t0Sieid3qbECjQs34rdTTSW#fidkdWxOYHwnPyd1blppbHNgWjA0T1BEcXJGPWR1VUpSbkFJSFR0S0M8dlV1Y2tgS1ZVa3JdPVxfPXw0Q0tBaTNzPDFtX0xyf2JDVlxpNzJnUkAxSmp2PUZJdHBwa1B2ck53TmZkQW1BSjNoNTU3XG88RGBObycpJ2N3amhWYHdzYHcnP3F3cGApJ2lkfGpwcVF8dWAnPyd2bGtiaWBabHFgaCcpJ2BrZGdpYFVpZGZgbWppYWB3dic%2FcXdwYHgl","paymentAmount":1000,"winc":"367209971237"}
Opening checkout session in browser...
```

feat(top-up): init top-up with stripe checkout command PE-6635

---

package.json
yarn.lock

Updates kyveJS so that turbo-sdk consumers no longer have to provide:
- `long`
- `@cosmjs/math`
- `cosmjs-types`
- `protobufjs`

chore: release v1.16.1

---

src/common/factory.ts
src/common/http.ts
src/common/signer.ts
src/common/token/solana.ts
src/node/factory.ts
src/node/upload.ts
src/types.ts
src/web/factory.ts
src/web/signer.ts
tests/turbo.web.test.ts

this PR implements ETH and SOL web signing for upload and crypto fund flows

PE-6052 -- feat(web): implement walletAdapter for SOL and ETH web signing support

---

package.json
yarn.lock

This dep changed the use of starknet, causing breaking changes when uploading with kyve. Pinning to a working version until we resolve.
Reference: https://github.com/chainapsis/keplr-wallet/commit/2a8ca006f1992de94c509bb5220b0d65ced927f5

fix(deps): pin `@keplr-wallet/cosmos` dependency

---

examples/web/index.html

There is an issue with our use of arweave causing errors on import.

chore(docs): pin web example to use 1.13.0.

---

src/cli/constants.ts
src/cli/utils.ts
src/common/logger.ts
src/common/signer.ts
src/common/token/baseEth.ts
src/common/token/ethereum.ts
src/common/token/index.ts
src/common/token/kyve.ts
src/common/token/polygon.ts
src/common/token/solana.ts
src/types.ts
src/utils/common.ts
tests/turbo.node.test.ts

```sh
> yarn build:esm && node lib/esm/cli/cli.js crypto-fund --token base-eth --wallet-file ../wallets/eth.pk.0x02f40b84CdDe657245049476E1E01DDffde6a21c.txt --payment-url http://localhost:3000 -v 0.0000001 --debug --dev --tx-id 0x2ebf23fc0d2b217ddcf0fd223ec98ba15c2c5a9c1e74bf96a1083a62072a22d2       
yarn run v1.22.22
$ yarn tsc -p tsconfig.json
$ /Users/derek/ar-io/ardrive-turbo-sdk/node_modules/.bin/tsc -p tsconfig.json
✨  Done in 3.96s.
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
(node:69522) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
debug: Uploading... {"loaded":"78 …
```

feat(eth on base): add methods/commands for funding ETH on base network for SDK and CLI PE-7481

---

package.json
yarn.lock

Ideally, this is just a peer dependency and does not impact downstream clients if they do not need it, but nextjs struggles to tree-shake this dep out as the `@kepler-wallet` deps require it as a peer depedency. In the future we should look how to extract the kyve implementation so it can be optionally added as a plugin/separte dep and only used when necessary.

fix(deps): include bitcoinjs-lib as a dependency

---

src/common/http.ts
src/common/upload.ts
src/types.ts
src/utils/readableStream.ts
src/web/events.ts
src/web/upload.ts
tests/turbo.web.test.ts

ReadableStream will be available by default for browser based clients. This is purely a type workaround as the tsconfig specificifies that `dom` types/classes are allowed, avoiding the need for direct imports from `node:streams/web`. One interesting problem to solve is if someone running a node environment, but wants to use ReadableStream exported by node:streams/web will typescript allow that? Not sure. This at least unblocks for now.

fix(streams): use native ReadableStream vs the node import

---

README.md
src/cli/cli.ts
src/cli/commands/fiatEstimate.ts
src/cli/commands/price.ts
src/cli/commands/tokenPrice.ts
src/cli/commands/topUp.ts
src/cli/types.ts
src/cli/utils.ts
src/common/payment.ts
src/common/turbo.ts
src/types.ts
tests/turbo.node.test.ts

this PR adds `fiat-estimate` command with optional `--currency` and required `--byte-count` options. it also adds `--currency` option to `price` command. when currency exists and price --type is bytes, we will use the fiatEstimate special path. this will result in two API calls -- could iterate this into the service level
In the below examples we compare the price estimate of the workflow to the payment API. On the bytes request we get the same winc result as expected. on the fiat estimates we get the amount of winc a user would receive the fiat. those values are expected to be close but not exact because fiat payments can only get fractional down its base value
400,000 bytes example:
```sh
> yarn build:esm && node lib/esm/cli/cli.js fiat-estimate --currency jpy --byte-count 400000
{ …
```

PE-8142: bytes to usd price
